# Generated by Django 4.2.4 on 2023-10-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingUser',
            fields=[
                ('waiting_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Waiting_User',
                'managed': False,
            },
        ),
    ]
