# Generated by Django 4.2.4 on 2023-10-16 11:19

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('contents', models.CharField(blank=True, max_length=500, null=True)),
                ('menu', ArrayField(models.CharField(max_length=100))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
    ]
